### ISSUE TITLE
raw results

### ISSUE THREAD

**Issue by ZhouZhang233** [MARMOTatZJU/SiamFCplusplus#1]
Could you pubish your SiamFC++ raw results for comparation ? 
Thx.
Btw, when will you pubish your source code?

**Comment by MARMOTatZJU** [comment]
The repo for publishing code is currently under construction. That will be another repo other than this (an organization repo. I will attach the link to that repo in our paper on arXiv.

**Comment by MARMOTatZJU** [comment]
Raw results will be included in that repo.

**Comment by ZhouZhang233** [comment]
OK! Thanks!
